# Generated by Django 4.2.21 on 2025-12-30 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_loan_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='returned',
        ),
    ]
